version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
  ignore:
  - dependency-name: "chalk"
  - dependency-name: "node-fetch"
  - dependency-name: "debug-level"
